---
title: 'Spatial RNA: Day 1'
author: "Alexis Garretson"
date: "2024-06-18"
output: html_document
---

```{r setup, include=FALSE}
setwd("..")

knitr::opts_chunk$set(echo = TRUE)

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(hdf5r))
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(rcartocolor))


download.file("https://raw.githubusercontent.com/smcclatchy/spatial-transcriptomics/main/code/spatial_utils.R", destfile = "scripts/spatial_utils.R")

source("scripts/spatial_utils.R")
```


```{r}
raw_st <- Load10X_Spatial(data.dir      = "../data/151673", 
                          filename      = "151673_raw_feature_bc_matrix.h5",
                          filter.matrix = FALSE)

filter_st <- Load10X_Spatial(data.dir      = "../data/151673", 
                          filename      = "151673_filtered_feature_bc_matrix.h5",
                          filter.matrix = FALSE)
```

```{r}
tissue_position <- read_csv("../data/151673/spatial/tissue_positions_list.csv",
                            col_names =F) %>% 
  column_to_rownames("X1")

colnames(tissue_position) <- c("in_tissue", 
                               "array_row", 
                               "array_col", 
                               "pxl_row_in_fullres", 
                               "pxl_col_in_fullres")

tissue_position <- tissue_position[Cells(raw_st),]
stopifnot(rownames(tissue_position) == Cells(raw_st))

raw_st    <- AddMetaData(object = raw_st,    metadata = tissue_position)
filter_st <- AddMetaData(object = filter_st, metadata = tissue_position)
```

```{r}
SpatialPlot(raw_st, group.by = "in_tissue", alpha = 0.3)
```
```{r}
raw_st@meta.data %>%
  ggplot(aes(as.logical(in_tissue), nCount_Spatial)) +
    geom_boxplot() +
    labs(title = 'UMI Counts in Tissue and Background',
         x     = 'In Tissue?',
         y     = 'Counts') +
  ggpubr::stat_compare_means()
```
```{r}
plot1 <- SpatialDimPlot(filter_st, alpha = c(0, 0)) + 
           NoLegend()
plot2 <- SpatialDimPlot(filter_st) + 
           NoLegend()
plot1 | plot2
```


```{r}
plot1 <- SpatialDimPlot(filter_st, alpha = c(0, 0)) + 
           NoLegend()
plot2 <- SpatialFeaturePlot(filter_st, features = "nCount_Spatial")
plot1 | plot2
plot1
plot2
```

```{r}
plot1 <- SpatialDimPlot(filter_st, alpha = c(0, 0)) + 
           NoLegend()
plot2 <- SpatialFeaturePlot(filter_st, features = "nFeature_Spatial")
plot1 | plot2
```

```{r}
ggplot(tissue_position, aes(y=-array_row, x=array_col, color=in_tissue)) +
  geom_point()
```


```{r}
paste(nrow(filter_st), "genes.")
counts     <- LayerData(filter_st, 'counts')
gene_sums  <- rowSums(counts)
keep_genes <- which(gene_sums > 0)

filter_st  <- filter_st[keep_genes,]
```
```{r}
mito_pattern <- '^[Mm][Tt]-'
mito_genes   <- rownames(counts)[grep(mito_pattern, rownames(counts))]
mito_genes

filter_st[["percent.mt"]] <- PercentageFeatureSet(filter_st, pattern = mito_pattern)

hist(FetchData(filter_st, "percent.mt")[,1],   main = "% Mitochondrial Genes",
     xlab = "%")

```

```{r}
mito_expr <- FetchData(filter_st, "percent.mt")[,1]
qqnorm(mito_expr, las = 1)
qqline(mito_expr)
```

```{r}
layout(matrix(1:2, ncol = 1))
hist(FetchData(filter_st, "nCount_Spatial")[,1],
     main = 'UMIs per Spot', xlab = 'Counts', las = 1)
hist(FetchData(filter_st, "nFeature_Spatial")[,1], 
     main = 'Genes per Spot', xlab = 'Genes', las = 1)
```


```{r}
mito_thr     <- 32
counts_thr   <- 14000
features_thr <- 5000
```

```{r}
keep <- FetchData(filter_st, "percent.mt")[,1]       < mito_thr
keep <- FetchData(filter_st, "nCount_Spatial")[,1]   < counts_thr   & keep
keep <- FetchData(filter_st, "nFeature_Spatial")[,1] < features_thr & keep

filter_st$keep <- keep
```

```{r}
SpatialDimPlot(filter_st, group.by = "keep")
```

```{r}
counts <- LayerData(filter_st, layer = 'counts')
hist(colSums(counts), breaks = 100, 
     main = "Histogram of Counts per Spot")
```
```{r}
filter_st <- NormalizeData(filter_st, 
                           normalization.method="RC",
                           scale.factor=10^6)
```
```{r}
Layers(filter_st)
head(colSums(LayerData(filter_st, "data")))
```

```{r}
Layers(filter_st)
head(colSums(LayerData(filter_st, "data")))
```

```{r}
filter_st <- FindVariableFeatures(filter_st)

VariableFeaturePlot(filter_st, log=F) + xlim(0, 20)

```

```{r}
spot_metadata <- read.table("../data/spot-meta.tsv", sep="\t")
# Subset to our sample
spot_metadata <- subset(spot_metadata, sample_name == 151673)
rownames(spot_metadata) <- spot_metadata$barcode
stopifnot(all(Cells(filter_st) %in% rownames(spot_metadata)))
spot_metadata <- spot_metadata[Cells(filter_st),]

filter_st <- AddMetaData(object = filter_st, metadata = spot_metadata[, c("layer_guess", "cell_count"), drop=FALSE])
```

```{r}
SpatialDimPlotColorSafe(filter_st[, !is.na(filter_st[[]]$layer_guess)], "layer_guess") + labs(fill="Layer")
```


```{r}
g <- ggplot(na.omit(filter_st[[]][, c("layer_guess", "cell_count")]),
            aes(x = layer_guess, y = cell_count)) + 
  geom_boxplot(outlier.shape = NA) +
  xlab("Layer") + 
  ylab("Cell Count") +
  theme_classic() + 
  geom_jitter(alpha=0.05)
g
```

```{r}
SpatialFeaturePlot(filter_st, "cell_count")
```

```{r}
g <- ggplot(na.omit(filter_st[[]][, c("layer_guess", "nCount_Spatial")]), aes(x = layer_guess, y = nCount_Spatial))
g <- g + geom_boxplot()
g
```

```{r}
lognorm_st <- NormalizeData(filter_st, 
                           assay                = "Spatial", 
                           normalization.method = "LogNormalize", 
                           scale.factor         = 1e6)
lognorm_st <- FindVariableFeatures(lognorm_st)

top15        <- head(VariableFeatures(lognorm_st), 15)
plot_lognorm <- VariableFeaturePlot(lognorm_st) + 
                  ggtitle("Variable Features - Log normalization")
plot_lognorm <- LabelPoints(plot = plot_lognorm, points = top15, repel = TRUE)

```
```{r}
plot_lognorm
```

```{r}
SpatialFeaturePlot(lognorm_st, slot="data", c("MOBP"))
SpatialFeaturePlot(lognorm_st, slot="data", c("PCP4"))
```

```{r}
filter_st <- SCTransform(filter_st, assay = "Spatial")
Assays(filter_st)
DefaultAssay(filter_st)
```

```{r}
layout(matrix(1:2, ncol = 1))
raw_counts_spatial <- LayerData(filter_st, layer = "counts", assay = "Spatial")
hist(colSums(raw_counts_spatial), main = "Raw counts (Spatial)")

corrected_counts_sct <- LayerData(filter_st, layer = "data", assay = "SCT")
hist(colSums(corrected_counts_sct), main = "Corrected counts (SCT)")
```

```{r}
top15SCT    <- head(VariableFeatures(filter_st), 15)
plot_sct    <- VariableFeaturePlot(filter_st) + 
                 ggtitle("Variable Features - SCT")
plot_sct    <- LabelPoints(plot = plot_sct, points = top15SCT, repel = TRUE)
plot_sct
```

```{r}
SpatialFeaturePlot(filter_st, slot="data", c("MOBP"))
SpatialFeaturePlot(filter_st, slot="data", c("PCP4"))
```

```{r}
layout(matrix(1:2, ncol = 1))
counts_log <- LayerData(lognorm_st, layer = "data")
hist(colSums(counts_log), main = "Log-norm")

counts_sct <- LayerData(filter_st, layer = "data")
hist(colSums(counts_sct), main = "SCT")
```

```{r}
plot_lognorm
```

```{r}
plot_sct
```

